import Head from 'next/head'
import Image from 'next/image'
import { Button } from 'react-bootstrap'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>

      <header className={styles.header}>
        <a href=""><Image src="/logo.png" alt="logo" width={75} height={75} /> </a>
        <a href="">BeeS</a>
        <a className={styles.button} href="login">Login</a>
      </header>

      <Head>
        <title>BeeS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Brazilian Enterprise of Efficient Storage <a href="login">(BeeS!)</a>
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Sobre &rarr;</h2>
            <p>Descubra mais sobre a aplicação favorita das abelhas!</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Login &rarr;</h2>
            <p>Crie a sua conta e obtenha a melhor colméia...</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        Copyright 2022.
      </footer>
    </div>
  )
}
